default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'training_app' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'training_app_development' } %>

test:
  <<: *default
  database: training_app_test

production:
  <<: *default
  database: training_app_production